/** 言語を定義 */
export const lang = {
    ja: {
      func: "機能",
      open: "開く",
      save: "保存",
      help: "ヘルプ",
      output: "PDF・HTML出力",
      print: "印刷",
      edit: "編集",
      insert: "挿入&クリップボードコピー",
      head1: "見出し1",
      head2: "見出し2",
      bold: "太字強調",
      bgbold: "背景強調",
      thead: "テーブルヘッダー",
      tseperate: "テーブル区切り",
      list: "箇条書き",
      numlist: "数値箇条書き",
      quote1: "引用1",
      quote2: "引用2",
      cancelline: "打消し線",
      checkbox: "チェックボックス",
      seperatepage: "改ページ",
      hidden: "折りたたみ※出力時は非表示",
      preview: "プレビュー",
      image: "画像",
      guide: "ガイド",
      theme: "テーマ",
      language: "言語",
      osslicenses: "OSS Licenses"
    },
    en: {
      func: "Functions",
      open: "Open",
      save: "Save",
      help: "Help",
      output: "PDF・HTML Output",
      print: "PrintOut",
      edit: "Edit",
      insert: "Insert & Clipboad Copy",
      head1: "Header1",
      head2: "Header2",
      bold: "Bold",
      bgbold: "BgColor",
      thead: "Table Header",
      tseperate: "Table Seperate",
      list: "List",
      numlist: "Number List",
      quote1: "Quote1",
      quote2: "Quote2",
      cancelline: "Cancel Line",
      checkbox: "CheckBox",
      seperatepage: "Separate Page",
      hidden: "Hiden",
      preview: "Preview",
      image: "Image",
      guide: "Guide",
      theme: "Theme",
      language: "Language",
      osslicenses: "OSS Licenses"
    },
  }